=== keymanapp/keyman/common/schemas/kmp/kmp.schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "$ref": "#/definitions/package",
  "definitions": {
    "package": {
      "type": "object",
      "properties": {
        "system": {
          "$ref": "#/definitions/system"
        },
        "options": {
          "$ref": "#/definitions/options"
        },
        "startMenu": {
          "$ref": "#/definitions/startMenu"
        },
        "strings": {
          "$ref": "#/definitions/strings"
        },
        "files": {
          "$ref": "#/definitions/files"
        },
        "keyboards": {
          "$ref": "#/definitions/keyboards"
        },
        "lexicalModels": {
          "$ref": "#/definitions/lexicalModels"
        },
        "info": {
          "$ref": "#/definitions/info"
        },
        "relatedPackages": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/relatedPackage"
          }
        }
      },
      "additionalProperties": false,
      "required": [
        "options",
        "system"
      ]
    },
    "system": {
      "type": "object",
      "properties": {
        "keymanDeveloperVersion": {
          "type": "string"
        },
        "fileVersion": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "fileVersion"
      ]
    },
    "options": {
      "type": "object",
      "properties": {
        "readmeFile": {
          "type": "string"
        },
        "graphicFile": {
          "type": "string"
        },
        "licenseFile": {
          "type": "string"
        },
        "welcomeFile": {
          "type": "string"
        },
        "executeProgram": {
          "type": "string"
        },
        "msiFilename": {
          "type": "string"
        },
        "msiOptions": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "startMenu": {
      "type": "object",
      "properties": {
        "folder": {
          "type": "string"
        },
        "addUninstallEntry": {
          "type": "boolean"
        },
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/startMenuItem"
          }
        }
      },
      "additionalProperties": false
    },
    "startMenuItem": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "filename": {
          "type": "string"
        },
        "arguments": {
          "type": "string"
        },
        "icon": {
          "type": "string"
        },
        "location": {
          "type": "number"
        }
      },
      "additionalProperties": false,
      "required": [
        "name",
        "filename"
      ]
    },
    "strings": {
      "type": "object",
      "patternProperties": {
        ".": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "files": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/file"
      }
    },
    "file": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "copyLocation": {
          "type": "number"
        }
      },
      "additionalProperties": false,
      "required": [
        "name",
        "description"
      ]
    },
    "keyboards": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/keyboard"
      }
    },
    "keyboard": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "oskFont": {
          "type": "string"
        },
        "displayFont": {
          "type": "string"
        },
        "rtl": {
          "type": "boolean"
        },
        "languages": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/keyboardLanguage"
          }
        },
        "examples": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/keyboardExample"
          }
        },
        "webOskFonts": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "webDisplayFonts": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "additionalProperties": false,
      "required": [
        "name",
        "id",
        "version"
      ]
    },
    "keyboardLanguage": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "id",
        "name"
      ]
    },
    "info": {
      "type": "object",
      "properties": {
        "website": {
          "$ref": "#/definitions/infoItem"
        },
        "version": {
          "$ref": "#/definitions/infoItem"
        },
        "name": {
          "$ref": "#/definitions/infoItem"
        },
        "copyright": {
          "$ref": "#/definitions/infoItem"
        },
        "author": {
          "$ref": "#/definitions/infoItem"
        },
        "description": {
          "$ref": "#/definitions/infoItem"
        }
      },
      "additionalProperties": false
    },
    "infoItem": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string"
        },
        "url": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "description"
      ]
    },
    "lexicalModels": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/lexicalModel"
      }
    },
    "lexicalModel": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "rtl": {
          "type": "boolean"
        },
        "languages": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/keyboardLanguage"
          }
        }
      },
      "additionalProperties": false,
      "required": [
        "name",
        "id",
        "languages"
      ]
    },
    "keyboardExample": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "keys": {
          "type": "string"
        },
        "text": {
          "type": "string"
        },
        "note": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "id",
        "keys"
      ]
    },
    "relatedPackage": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "relationship": {
          "type": "string",
          "enum": ["deprecates", "related"]
        }
      },
      "additionalProperties": false,
      "required": [
        "id",
        "relationship"
      ]
    }
  }
}

=== keymanapp/keyman/mac/KeymanSettings/Tests/Resources/amharic.kmp.json
{
  "system": {
    "fileVersion": "15.0",
    "keymanDeveloperVersion": "17.0.330"
  },
  "options": {
    "graphicFile": "sideimage.bmp",
    "readmeFile": "readme.htm",
    "licenseFile": "LICENSE.md",
    "welcomeFile": "welcome.htm"
  },
  "info": {
    "author": {
      "description": "The Geʾez Frontier Foundation",
      "url": "mailto:keyboards@ethiopic.org"
    },
    "copyright": {
      "description": "© Geʾez Frontier Foundation, SIL International"
    },
    "name": {
      "description": "GFF Amharic Keyboard"
    },
    "version": {
      "description": "3.1.2"
    },
    "website": {
      "description": "http://keyboards.ethiopic.org",
      "url": "http://keyboards.ethiopic.org"
    },
    "description": {
      "description": "<p>This is an Amharic (amh, አማርኛ) language mnemonic input method. It\nrequires a font supporting Ethiopic script under the Unicode 4.1\nstandard.</p>"
    }
  },
  "relatedPackages": [
    {
      "id": "gff_amh_powerpack_7",
      "relationship": "deprecates"
    },
    {
      "id": "gff_amh_7",
      "relationship": "deprecates"
    }
  ],
  "files": [
    {
      "name": "readme.htm",
      "description": "File readme.htm"
    },
    {
      "name": "sideimage.bmp",
      "description": "File sideimage.bmp"
    },
    {
      "name": "AmharicTyping-Amharic.pdf",
      "description": "File AmharicTyping-Amharic.pdf"
    },
    {
      "name": "AmharicTyping-English.pdf",
      "description": "File AmharicTyping-English.pdf"
    },
    {
      "name": "OFL.txt",
      "description": "File OFL.txt"
    },
    {
      "name": "GNU-GPLv2.txt",
      "description": "File GNU-GPLv2.txt"
    },
    {
      "name": "welcome.htm",
      "description": "File welcome.htm"
    },
    {
      "name": "fantuwua.ttf",
      "description": "Font Ethiopic Fantuwua"
    },
    {
      "name": "FreeSerif.otf",
      "description": "Font Free Serif"
    },
    {
      "name": "goffer.ttf",
      "description": "Font Ethiopic Yigezu Bisrat Goffer"
    },
    {
      "name": "hiwua.ttf",
      "description": "Font Ethiopic Hiwua"
    },
    {
      "name": "jiret.ttf",
      "description": "Font Ethiopia Jiret"
    },
    {
      "name": "jiretsl.ttf",
      "description": "Font Ethiopia Jiret Slant"
    },
    {
      "name": "tint.ttf",
      "description": "Font Ethiopic Tint"
    },
    {
      "name": "washrab.ttf",
      "description": "Font Ethiopic WashRa Bold"
    },
    {
      "name": "washrabsl.ttf",
      "description": "Font Ethiopic WashRa Bold Slant"
    },
    {
      "name": "washrasb.ttf",
      "description": "Font Ethiopic WashRa SemiBold"
    },
    {
      "name": "washrasbsl.ttf",
      "description": "Font Ethiopic WashRa SemiBold Slant"
    },
    {
      "name": "wookianos.ttf",
      "description": "Font Ethiopic Wookianos"
    },
    {
      "name": "yebse.ttf",
      "description": "Font Ethiopic Yebse"
    },
    {
      "name": "gff_amharic.js",
      "description": "File gff_amharic.js"
    },
    {
      "name": "gff_amharic.kmx",
      "description": "Keyboard አማርኛ (Amharic)"
    },
    {
      "name": "Brana-Regular.ttf",
      "description": "Font Brana"
    },
    {
      "name": "gff_amharic.kvk",
      "description": "File gff_amharic.kvk"
    },
    {
      "name": "AbyssinicaSIL-Regular.ttf",
      "description": "Font Abyssinica SIL"
    },
    {
      "name": "AbyssinicaSILConnected-Regular.ttf",
      "description": "Font Abyssinica SIL Connected"
    },
    {
      "name": "LICENSE.md",
      "description": ""
    },
    {
      "name": "kmp.inf",
      "description": "Package information"
    },
    {
      "name": "kmp.json",
      "description": "Package information (JSON)"
    }
  ],
  "keyboards": [
    {
      "displayFont": "AbyssinicaSIL-Regular.ttf",
      "oskFont": "AbyssinicaSIL-Regular.ttf",
      "name": "አማርኛ (Amharic)",
      "id": "gff_amharic",
      "version": "3.1.2",
      "languages": [
        {
          "name": "Amharic",
          "id": "am"
        }
      ],
      "examples": [
        {
          "id": "am",
          "keys": "T i e n a space y s T l N",
          "text": "ጤና ይስጥልኝ",
          "note": "\"Hello\""
        }
      ]
    }
  ],
  "startMenu": {
    "addUninstallEntry": true,
    "folder": "GFF Amharic Keyboard",
    "items": [
      {
        "filename": "welcome.htm",
        "name": "Welcome"
      },
      {
        "filename": "AmharicTyping-Amharic.pdf",
        "name": "Amharic Keyboard Manual (Amharic)"
      },
      {
        "filename": "AmharicTyping-English.pdf",
        "name": "Amharic Keyboard Manual (English)"
      },
      {
        "filename": "OFL.txt",
        "name": "OFL (Abyssinica SIL Licence)"
      },
      {
        "filename": "GNU-GPLv2.txt",
        "name": "GPL (WashRa + Free Serif Licence)"
      },
      {
        "filename": "http://keyboards.ethiopic.org/docs/AmharicTypingPractice.docx",
        "name": "Amharic Typing Practice"
      }
    ]
  }
}

=== keymanapp/keyman/linux/ibus-keyman/src/test/testdata/kmp.json
{
  "system": {
    "keymanDeveloperVersion": "10.0.1202.0",
    "fileVersion": "7.0"
  },
  "options": {
    "readmeFile": "readme.htm"
  },
  "info": {
    "version": {
      "description": "1.6.1"
    },
    "name": {
      "description": "LIBTRALO"
    },
    "copyright": {
      "description": "\u00A9 2008-2018 SIL Global"
    },
    "author": {
      "description": "support@keyman.com",
      "url": "mailto:support@keyman.com"
    }
  },
  "files": [
    {
      "name": "libtralo.kmx",
      "description": "Keyboard LIBTRALO"
    },
    {
      "name": "readme.htm",
      "description": "File readme.htm"
    },
    {
      "name": "libtralo.png",
      "description": "File libtralo.png"
    },
    {
      "name": "welcome.htm",
      "description": "File welcome.htm"
    },
    {
      "name": "Charis_SIL_README.txt",
      "description": "File Charis_SIL_README.txt"
    },
    {
      "name": "CharisSIL-B.ttf",
      "description": "Font Charis SIL Bold"
    },
    {
      "name": "CharisSIL-BI.ttf",
      "description": "Font Charis SIL Bold Italic"
    },
    {
      "name": "CharisSIL-I.ttf",
      "description": "Font Charis SIL Italic"
    },
    {
      "name": "CharisSIL-R.ttf",
      "description": "Font Charis SIL"
    },
    {
      "name": "FONTLOG.txt",
      "description": "File FONTLOG.txt"
    },
    {
      "name": "OFL.txt",
      "description": "File OFL.txt"
    },
    {
      "name": "OFL-FAQ.txt",
      "description": "File OFL-FAQ.txt"
    },
    {
      "name": "CharisSILDan-Bold.ttf",
      "description": "Font Charis SIL Dan Bold"
    },
    {
      "name": "CharisSILDan-BoldItalic.ttf",
      "description": "Font Charis SIL Dan Bold Italic"
    },
    {
      "name": "CharisSILDan-Italic.ttf",
      "description": "Font Charis SIL Dan Italic"
    },
    {
      "name": "CharisSILDan-Regular.ttf",
      "description": "Font Charis SIL Dan"
    },
    {
      "name": "libtralo.js",
      "description": "File libtralo.js"
    },
    {
      "name": "libtralo.kvk",
      "description": "File libtralo.kvk"
    },
    {
      "name": "CharisSILDan_FONTLOG.txt",
      "description": "File CharisSILDan_FONTLOG.txt"
    },
    {
      "name": "kmp.inf",
      "description": "Package information"
    },
    {
      "name": "kmp.json",
      "description": "Package information (JSON)"
    }
  ],
  "keyboards": [
    {
      "name": "LIBTRALO",
      "id": "libtralo",
      "version": "1.6.1",
      "languages": [
        {
          "name": "Bandi",
          "id": "bza-Latn"
        },
        {
          "name": "Bassa",
          "id": "bsq-Latn"
        },
        {
          "name": "Glio-Oubi",
          "id": "oub-Latn"
        },
        {
          "name": "Gola",
          "id": "gol-Latn"
        },
        {
          "name": "Northern Grebo",
          "id": "gbo-Latn"
        },
        {
          "name": "Southern Kisi",
          "id": "kss-Latn"
        },
        {
          "name": "Klao",
          "id": "klu-Latn"
        },
        {
          "name": "Liberia Kpelle (Latin)",
          "id": "xpe-Latn"
        },
        {
          "name": "Eastern Krahn",
          "id": "kqo-Latn"
        },
        {
          "name": "Western Krahn",
          "id": "krw-Latn"
        },
        {
          "name": "Kuwaa",
          "id": "blh-Latn"
        },
        {
          "name": "Loma (Liberia) (Latin)",
          "id": "lom-Latn"
        },
        {
          "name": "Mano",
          "id": "mev-Latn"
        },
        {
          "name": "Manya",
          "id": "mzj-Latn"
        },
        {
          "name": "Sapo",
          "id": "krn-Latn"
        },
        {
          "name": "Bullom So",
          "id": "buy-Latn"
        },
        {
          "name": "Kono (Sierra Leone)",
          "id": "kno-Latn"
        },
        {
          "name": "Krio",
          "id": "kri-Latn"
        },
        {
          "name": "Kuranko",
          "id": "knk-Latn"
        },
        {
          "name": "West-Central Limba",
          "id": "lia-Latn"
        },
        {
          "name": "Loko",
          "id": "lok-Latn"
        },
        {
          "name": "Mende (Sierra Leone)",
          "id": "men"
        },
        {
          "name": "Timne",
          "id": "tem"
        },
        {
          "name": "Vai (Latin)",
          "id": "vai-Latn"
        },
        {
          "name": "Dewoin (Latin)",
          "id": "dee-Latn"
        },
        {
          "name": "Dan (Western) (Latin)",
          "id": "dnj-Latn-LR"
        },
        {
          "name": "Gbii (Latin)",
          "id": "ggb-Latn"
        },
        {
          "name": "Glaro-Twabo (Latin)",
          "id": "glr-Latn"
        },
        {
          "name": "Grebo (Latin)",
          "id": "grb-Latn"
        },
        {
          "name": "Barclayville Grebo (Latin)",
          "id": "gry-Latn"
        },
        {
          "name": "Central Grebo (Latin)",
          "id": "grv-Latn"
        },
        {
          "name": "Gboloo Grebo (Latin)",
          "id": "gec-Latn"
        },
        {
          "name": "Southern Grebo (Latin)",
          "id": "grj-Latn"
        },
        {
          "name": "Kpelle (Latin)",
          "id": "kpe-Latn"
        },
        {
          "name": "Tajuasohn (Latin)",
          "id": "tja-Latn"
        },
        {
          "name": "Bom-Kim (Latin)",
          "id": "bmf-Latn"
        },
        {
          "name": "Sherbro (Latin)",
          "id": "bun-Latn"
        }
      ]
    }
  ]
}

=== keymanapp/keyman/developer/src/kmc-package/test/fixtures/withfolders.qaa.sencoten/withfolders.qaa.sencoten.model.kmp.intermediate.json
{
  "system": {
    "keymanDeveloperVersion": "12.0.1500.0",
    "fileVersion": "12.0"
  },
  "options": {},
  "info": {
    "author": {
      "description": "Eddie Antonio Santos",
      "url": "mailto:Eddie.Santos@nrc-cnrc.gc.ca"
    },
    "copyright": {
      "description": "© 2019 National Research Council Canada"
    },
    "name": {
      "description": "SENĆOŦEN (Saanich Dialect) Lexical Model"
    },
    "version": {
      "description": "1.0.3"
    }
  },
  "files": [
    {
      "name": "..\\build\\withfolders.qaa.sencoten.model.js",
      "description": "Lexical model withfolders.qaa.sencoten.model.js"
    },
    {
      "description": "Welcome file",
      "name": "welcome.htm"
    },
    {
      "description": "Package information (JSON)",
      "name": "kmp.json"
    }
  ],
  "lexicalModels": [
    {
      "name": "SENĆOŦEN dictionary",
      "id": "withfolders.qaa.sencoten",
      "languages": [
        {
          "name": "North Straits Salish",
          "id": "qaa"
        },
        {
          "name": "SENĆOŦEN",
          "id": "qaa-Latn"
        }
      ]
    }
  ]
}

=== keymanapp/keyman/developer/src/kmc-package/test/fixtures/kmp.inf/kmp.json
{
  "system": {
    "keymanDeveloperVersion": "17.0.91.0",
    "fileVersion": "7.0"
  },
  "options": {
    "readmeFile": "readme.htm"
  },
  "startMenu": {
    "folder": "Thamizha Tamil99",
    "addUninstallEntry": true,
    "items": [
      {
        "name": "Using Tamil99 Keyboard",
        "filename": "welcome.htm"
      }
    ]
  },
  "info": {
    "name": {
      "description": "Thamizha Tamil99"
    },
    "copyright": {
      "description": "\u00A9 2008, 2015, 2018-2023 thamizha.com and SIL International"
    },
    "version": {
      "description": "2.0.4"
    },
    "author": {
      "description": "Mugunth, Umar, K. Sethu",
      "url": "mailto:mugunth@gmail.com"
    },
    "website": {
      "description": "http://www.thamizha.com",
      "url": "http://www.thamizha.com"
    }
  },
  "files": [
    {
      "name": "ekwtamil99uni.kvk",
      "description": "File ekwtamil99uni.kvk"
    },
    {
      "name": "ekwtamil99uni.kmx",
      "description": "Keyboard \u0BA4\u0BAE\u0BBF\u0BB4\u0BCD99 | Tamil99"
    },
    {
      "name": "readme.htm",
      "description": "File readme.htm"
    },
    {
      "name": "welcome.htm",
      "description": "File welcome.htm"
    },
    {
      "name": "keyrenderer.js",
      "description": "File keyrenderer.js"
    },
    {
      "name": "keys2.gif",
      "description": "File keys2.gif"
    },
    {
      "name": "style.css",
      "description": "File style.css"
    },
    {
      "name": "tr.gif",
      "description": "File tr.gif"
    },
    {
      "name": "aava1.ttf",
      "description": "Font aAvarangal"
    },
    {
      "name": "key-altl.gif",
      "description": "File key-altl.gif"
    },
    {
      "name": "key-altr.gif",
      "description": "File key-altr.gif"
    },
    {
      "name": "key-backspace.gif",
      "description": "File key-backspace.gif"
    },
    {
      "name": "key-bkslash.gif",
      "description": "File key-bkslash.gif"
    },
    {
      "name": "keyboardchart.htm",
      "description": "File keyboardchart.htm"
    },
    {
      "name": "key-capslock.gif",
      "description": "File key-capslock.gif"
    },
    {
      "name": "key-ctrll.gif",
      "description": "File key-ctrll.gif"
    },
    {
      "name": "key-ctrlr.gif",
      "description": "File key-ctrlr.gif"
    },
    {
      "name": "key-enter.gif",
      "description": "File key-enter.gif"
    },
    {
      "name": "key-plain.gif",
      "description": "File key-plain.gif"
    },
    {
      "name": "key-shift102.gif",
      "description": "File key-shift102.gif"
    },
    {
      "name": "key-shiftl.gif",
      "description": "File key-shiftl.gif"
    },
    {
      "name": "key-shiftr.gif",
      "description": "File key-shiftr.gif"
    },
    {
      "name": "key-space.gif",
      "description": "File key-space.gif"
    },
    {
      "name": "key-tab.gif",
      "description": "File key-tab.gif"
    },
    {
      "name": "sri.png",
      "description": "File sri.png"
    },
    {
      "name": "ekwtamil99uni.js",
      "description": "File ekwtamil99uni.js"
    },
    {
      "name": "kmp.inf",
      "description": "Package information"
    },
    {
      "name": "kmp.json",
      "description": "Package information (JSON)"
    }
  ],
  "keyboards": [
    {
      "name": "\u0BA4\u0BAE\u0BBF\u0BB4\u0BCD99 | Tamil99",
      "id": "ekwtamil99uni",
      "version": "2.0.4",
      "languages": [
        {
          "name": "Tamil",
          "id": "ta"
        }
      ]
    }
  ]
}

=== keymanapp/keyman/linux/ibus-keyman/src/test/testdata/kmp1.json
{
  "system": {
    "keymanDeveloperVersion": "10.0.1202.0",
    "fileVersion": "7.0"
  },
  "options": {
    "readmeFile": "readme.htm"
  },
  "info": {
    "version": {
      "description": "1.6.1"
    },
    "name": {
      "description": "LIBTRALO"
    },
    "copyright": {
      "description": "\u00A9 2008-2018 SIL International"
    },
    "author": {
      "description": "support@keyman.com",
      "url": "mailto:support@keyman.com"
    }
  },
  "files": [
    {
      "name": "libtralo.kmx",
      "description": "Keyboard LIBTRALO"
    },
    {
      "name": "readme.htm",
      "description": "File readme.htm"
    },
    {
      "name": "libtralo.png",
      "description": "File libtralo.png"
    },
    {
      "name": "welcome.htm",
      "description": "File welcome.htm"
    },
    {
      "name": "Charis_SIL_README.txt",
      "description": "File Charis_SIL_README.txt"
    },
    {
      "name": "CharisSIL-B.ttf",
      "description": "Font Charis SIL Bold"
    },
    {
      "name": "CharisSIL-BI.ttf",
      "description": "Font Charis SIL Bold Italic"
    },
    {
      "name": "CharisSIL-I.ttf",
      "description": "Font Charis SIL Italic"
    },
    {
      "name": "CharisSIL-R.ttf",
      "description": "Font Charis SIL"
    },
    {
      "name": "FONTLOG.txt",
      "description": "File FONTLOG.txt"
    },
    {
      "name": "OFL.txt",
      "description": "File OFL.txt"
    },
    {
      "name": "OFL-FAQ.txt",
      "description": "File OFL-FAQ.txt"
    },
    {
      "name": "CharisSILDan-Bold.ttf",
      "description": "Font Charis SIL Dan Bold"
    },
    {
      "name": "CharisSILDan-BoldItalic.ttf",
      "description": "Font Charis SIL Dan Bold Italic"
    },
    {
      "name": "CharisSILDan-Italic.ttf",
      "description": "Font Charis SIL Dan Italic"
    },
    {
      "name": "CharisSILDan-Regular.ttf",
      "description": "Font Charis SIL Dan"
    },
    {
      "name": "libtralo.js",
      "description": "File libtralo.js"
    },
    {
      "name": "libtralo.kvk",
      "description": "File libtralo.kvk"
    },
    {
      "name": "CharisSILDan_FONTLOG.txt",
      "description": "File CharisSILDan_FONTLOG.txt"
    },
    {
      "name": "kmp.inf",
      "description": "Package information"
    },
    {
      "name": "kmp.json",
      "description": "Package information (JSON)"
    }
  ],
  "keyboards": [
    {
      "name": "TEST1",
      "id": "test1",
      "version": "1.6.1",
      "languages": [
        {
          "name": "Bandi",
          "id": "bza-Latn"
        }
      ]
    }
  ]
}
