=== keymanapp/keyman/common/schemas/kmp/kmp.schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "$ref": "#/definitions/package",
  "definitions": {
    "package": {
      "type": "object",
      "properties": {
        "system": {
          "$ref": "#/definitions/system"
        },
        "options": {
          "$ref": "#/definitions/options"
        },
        "startMenu": {
          "$ref": "#/definitions/startMenu"
        },
        "strings": {
          "$ref": "#/definitions/strings"
        },
        "files": {
          "$ref": "#/definitions/files"
        },
        "keyboards": {
          "$ref": "#/definitions/keyboards"
        },
        "lexicalModels": {
          "$ref": "#/definitions/lexicalModels"
        },
        "info": {
          "$ref": "#/definitions/info"
        },
        "relatedPackages": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/relatedPackage"
          }
        }
      },
      "additionalProperties": false,
      "required": [
        "options",
        "system"
      ]
    },
    "system": {
      "type": "object",
      "properties": {
        "keymanDeveloperVersion": {
          "type": "string"
        },
        "fileVersion": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "fileVersion"
      ]
    },
    "options": {
      "type": "object",
      "properties": {
        "readmeFile": {
          "type": "string"
        },
        "graphicFile": {
          "type": "string"
        },
        "licenseFile": {
          "type": "string"
        },
        "welcomeFile": {
          "type": "string"
        },
        "executeProgram": {
          "type": "string"
        },
        "msiFilename": {
          "type": "string"
        },
        "msiOptions": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "startMenu": {
      "type": "object",
      "properties": {
        "folder": {
          "type": "string"
        },
        "addUninstallEntry": {
          "type": "boolean"
        },
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/startMenuItem"
          }
        }
      },
      "additionalProperties": false
    },
    "startMenuItem": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "filename": {
          "type": "string"
        },
        "arguments": {
          "type": "string"
        },
        "icon": {
          "type": "string"
        },
        "location": {
          "type": "number"
        }
      },
      "additionalProperties": false,
      "required": [
        "name",
        "filename"
      ]
    },
    "strings": {
      "type": "object",
      "patternProperties": {
        ".": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "files": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/file"
      }
    },
    "file": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "copyLocation": {
          "type": "number"
        }
      },
      "additionalProperties": false,
      "required": [
        "name",
        "description"
      ]
    },
    "keyboards": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/keyboard"
      }
    },
    "keyboard": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "oskFont": {
          "type": "string"
        },
        "displayFont": {
          "type": "string"
        },
        "rtl": {
          "type": "boolean"
        },
        "languages": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/keyboardLanguage"
          }
        },
        "examples": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/keyboardExample"
          }
        },
        "webOskFonts": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "webDisplayFonts": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "additionalProperties": false,
      "required": [
        "name",
        "id",
        "version"
      ]
    },
    "keyboardLanguage": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "id",
        "name"
      ]
    },
    "info": {
      "type": "object",
      "properties": {
        "website": {
          "$ref": "#/definitions/infoItem"
        },
        "version": {
          "$ref": "#/definitions/infoItem"
        },
        "name": {
          "$ref": "#/definitions/infoItem"
        },
        "copyright": {
          "$ref": "#/definitions/infoItem"
        },
        "author": {
          "$ref": "#/definitions/infoItem"
        },
        "description": {
          "$ref": "#/definitions/infoItem"
        }
      },
      "additionalProperties": false
    },
    "infoItem": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string"
        },
        "url": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "description"
      ]
    },
    "lexicalModels": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/lexicalModel"
      }
    },
    "lexicalModel": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "rtl": {
          "type": "boolean"
        },
        "languages": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/keyboardLanguage"
          }
        }
      },
      "additionalProperties": false,
      "required": [
        "name",
        "id",
        "languages"
      ]
    },
    "keyboardExample": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "keys": {
          "type": "string"
        },
        "text": {
          "type": "string"
        },
        "note": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "id",
        "keys"
      ]
    },
    "relatedPackage": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "relationship": {
          "type": "string",
          "enum": ["deprecates", "related"]
        }
      },
      "additionalProperties": false,
      "required": [
        "id",
        "relationship"
      ]
    }
  }
}

=== keymanapp/keyman/android/KMEA/test_resources/packages/galaxie_greek_hebrew_mnemonic/kmp.json
{
  "system": {
    "keymanDeveloperVersion": "10.0.1206.0",
    "fileVersion": "7.0"
  },
  "options": {
    "readmeFile": "readme.htm"
  },
  "info": {
    "name": {
      "description": "Galaxie Greek/Hebrew (Mnemonic) Keyboard Package"
    },
    "copyright": {
      "description": "2004-2018 Galaxie Software and SIL International"
    },
    "version": {
      "description": "3.2"
    }
  },
  "files": [
    {
      "name": "greek-welcome.htm",
      "description": "File greek-welcome.htm"
    },
    {
      "name": "hebrew-welcome.htm",
      "description": "File hebrew-welcome.htm"
    },
    {
      "name": "style.css",
      "description": "File style.css"
    },
    {
      "name": "welcome.htm",
      "description": "File welcome.htm"
    },
    {
      "name": "readme.htm",
      "description": "File readme.htm"
    },
    {
      "name": "galaxie_hebrew_mnemonic.js",
      "description": "File galaxie_hebrew_mnemonic.js"
    },
    {
      "name": "galaxie_hebrew_mnemonic.kvk",
      "description": "File galaxie_hebrew_mnemonic.kvk"
    },
    {
      "name": "galaxie_hebrew_mnemonic.kmx",
      "description": "Keyboard Galaxie Hebrew (Mnemonic)"
    },
    {
      "name": "galaxie_greek_mnemonic.js",
      "description": "File galaxie_greek_mnemonic.js"
    },
    {
      "name": "galaxie_greek_mnemonic.kvk",
      "description": "File galaxie_greek_mnemonic.kvk"
    },
    {
      "name": "galaxie_greek_mnemonic.kmx",
      "description": "Keyboard Galaxie Greek (Mnemonic)"
    },
    {
      "name": "kmp.inf",
      "description": "Package information"
    },
    {
      "name": "kmp.json",
      "description": "Package information (JSON)"
    }
  ],
  "keyboards": [
    {
      "name": "Galaxie Hebrew (Mnemonic)",
      "id": "galaxie_hebrew_mnemonic",
      "version": "3.2",
      "languages": [
        {
          "name": "Ancient Hebrew (Hebrew)",
          "id": "hbo-Hebr"
        },
        {
          "name": "Hebrew (Hebrew)",
          "id": "he-Hebr"
        },
        {
          "name": "Afade (Latin)",
          "id": "aal-Latn"
        }
      ]
    },
    {
      "name": "Galaxie Greek (Mnemonic)",
      "id": "galaxie_greek_mnemonic",
      "version": "3.2.1",
      "languages": [
        {
          "name": "Ancient Greek (to 1453) (Greek)",
          "id": "grc-Grek"
        },
        {
          "name": "Modern Greek (1453-) (Greek)",
          "id": "el-Grek"
        }
      ]
    }
  ]
}

=== keymanapp/keyman/developer/src/kmc-package/test/fixtures/kmp_2.0/kmp.json
{
  "system": {
    "keymanDeveloperVersion": "16.0.60.0",
    "fileVersion": "7.0"
  },
  "options": {
    "readmeFile": "readme.htm",
    "graphicFile": "splash.gif"
  },
  "info": {
    "name": {
      "description": "Khmer Angkor"
    },
    "copyright": {
      "description": "\u00A9 2015-2022 SIL International"
    },
    "author": {
      "description": "Makara Sok",
      "url": "mailto:makara_sok@sil.org"
    },
    "version": {
      "description": "1.3"
    },
    "website": {
      "description": "https://keyman.com/keyboards/khmer_angkor",
      "url": "https://keyman.com/keyboards/khmer_angkor"
    },
    "description": {
      "description": "<h1>Khmer Angkor</h1>\n<p>Khmer Unicode keyboard layout based on the NiDA keyboard layout. Automatically corrects many common keying errors, including:</p>\n<ul>\n<li>Using wrong vowel combination</li>\n<li>Typing clusters out of order</li>\n<li>Typing wrong mark for consonant shifters</li>\n<li>And more!</li>\n</ul>"
    }
  },
  "files": [
    {
      "name": "khmer_angkor.js",
      "description": ""
    },
    {
      "name": "khmer_angkor.kvk",
      "description": ""
    },
    {
      "name": "khmer_angkor.kmx",
      "description": ""
    },
    {
      "name": "keyboard_layout.png",
      "description": ""
    },
    {
      "name": "welcome.htm",
      "description": ""
    },
    {
      "name": "FONTLOG.txt",
      "description": ""
    },
    {
      "name": "Mondulkiri-R.ttf",
      "description": ""
    },
    {
      "name": "OFL.txt",
      "description": ""
    },
    {
      "name": "OFL-FAQ.txt",
      "description": ""
    },
    {
      "name": "KAK_Documentation_EN.pdf",
      "description": ""
    },
    {
      "name": "KAK_Documentation_KH.pdf",
      "description": ""
    },
    {
      "name": "readme.htm",
      "description": ""
    },
    {
      "name": "image002.png",
      "description": ""
    },
    {
      "name": "khmer_busra_kbd.ttf",
      "description": ""
    },
    {
      "description": "",
      "name": "DejaVuSans.ttf"
    },
    {
      "name": "splash.gif",
      "description": ""
    },
    {
      "name": "kmp.inf",
      "description": ""
    },
    {
      "name": "kmp.json",
      "description": ""
    }
  ],
  "keyboards": [
    {
      "name": "Khmer Angkor",
      "id": "khmer_angkor",
      "version": "1.3",
      "oskFont": "khmer_busra_kbd.ttf",
      "displayFont": "Mondulkiri-R.ttf",
      "webOskFonts": ["khmer_busra_kbd.ttf"],
      "webDisplayFonts": ["DejaVuSans.ttf"],
      "languages": [
        {
          "name": "Central Khmer (Khmer, Cambodia)",
          "id": "km"
        }
      ],
      "examples": [
        {
          "id": "km",
          "keys": "x j m E r",
          "text": "ខ្មែរ",
          "note": "Name of language"
        },
        {
          "id": "km",
          "keys": "B j r H r a C a N a c k j r k m j B u C a",
          "text": "ព្រះរាជាណាចក្រកម្ពុជា",
          "note": "'Kingdom of Cambodia'"
        }
      ]
    }
  ],
  "relatedPackages": [
    { "id": "modern_khmer", "relationship": "deprecates" },
    { "id": "khmer_nida", "relationship": "related" }
  ]
}

=== keymanapp/keyman/developer/src/kmc-package/test/fixtures/example.qaa.sencoten/example.qaa.sencoten.model.kmp.json
{
  "system": {
    "keymanDeveloperVersion": "12.0.1500.0",
    "fileVersion": "12.0"
  },
  "options": {},
  "info": {
    "author": {
      "description": "Eddie Antonio Santos",
      "url": "mailto:Eddie.Santos@nrc-cnrc.gc.ca"
    },
    "copyright": {
      "description": "© 2019 National Research Council Canada"
    },
    "name": {
      "description": "SENĆOŦEN (Saanich Dialect) Lexical Model"
    },
    "version": {
      "description": "0.0.0"
    }
  },
  "files": [
    {
      "name": "..\\build\\example.qaa.sencoten.model.js",
      "description": "Lexical model example.qaa.sencoten.model.js"
    },
    {
      "name": "kmp.json",
      "description": "Package information (JSON)"
    }
  ],
  "lexicalModels": [
    {
      "name": "SENĆOŦEN dictionary",
      "id": "example.qaa.sencoten",
      "languages": [
        {
          "name": "North Straits Salish",
          "id": "qaa"
        },
        {
          "name": "SENĆOŦEN",
          "id": "qaa-Latn"
        }
      ]
    }
  ]
}

=== keymanapp/keyman/common/engine/keyboardprocessor/tests/unit/kmx/kmp.json
{
  "system": {
    "keymanDeveloperVersion": "10.0.1099.0",
    "fileVersion": "7.0"
  },
  "options": {
    "readmeFile": "kmx.cpp"
  },
  "info": {
    "name": {
      "description": "Test Keyboards"
    },
    "version": {
      "description": "0.0"
    },
    "copyright": {
      "description": "\u00A9 2018 SIL International"
    },
    "author": {
      "description": ""
    }
  },
  "files": [
    {
      "name": "kmp.json",
      "description": "Package information (JSON)"
    }
  ],
  "keyboards": [
    {
      "name": "000 - null keyboard",
      "id": "000 - null keyboard",
      "version": "0.0",
      "languages": [
        {
          "name": "Undetermined",
          "id": "und"
        }
      ]
    },
    {
      "name": "001 - basic input UnicodeI",
      "id": "001 - basic input UnicodeI",
      "version": "0.0",
      "languages": [
        {
          "name": "Undetermined",
          "id": "und"
        }
      ]
    },
    {
      "name": "002 - basic input Unicode",
      "id": "002 - basic input Unicode",
      "version": "0.0",
      "languages": [
        {
          "name": "Undetermined",
          "id": "und"
        }
      ]
    },
    {
      "name": "003 - nul",
      "id": "003 - nul",
      "version": "0.0",
      "languages": [
        {
          "name": "Undetermined",
          "id": "und"
        }
      ]
    },
    {
      "name": "004 - basic input (shift 2)",
      "id": "004 - basic input (shift 2)",
      "version": "0.0",
      "languages": [
        {
          "name": "Undetermined",
          "id": "und"
        }
      ]
    },
    {
      "name": "005 - nul with initial context",
      "id": "005 - nul with initial context",
      "version": "0.0",
      "languages": [
        {
          "name": "Undetermined",
          "id": "und"
        }
      ]
    },
    {
      "name": "006 - vkey input (shift ctrl)",
      "id": "006 - vkey input (shift ctrl)",
      "version": "0.0",
      "languages": [
        {
          "name": "Undetermined",
          "id": "und"
        }
      ]
    },
    {
      "name": "007 - vkey input (ctrl alt)",
      "id": "007 - vkey input (ctrl alt)",
      "version": "0.0",
      "languages": [
        {
          "name": "Undetermined",
          "id": "und"
        }
      ]
    },
    {
      "name": "008 - vkey input (ctrl alt 2)",
      "id": "008 - vkey input (ctrl alt 2)",
      "version": "0.0",
      "languages": [
        {
          "name": "Undetermined",
          "id": "und"
        }
      ]
    },
    {
      "name": "012 - ralt",
      "id": "012 - ralt",
      "version": "0.0",
      "languages": [
        {
          "name": "Undetermined",
          "id": "und"
        }
      ]
    },
    {
      "name": "013 - deadkeys",
      "id": "013 - deadkeys",
      "version": "0.0",
      "languages": [
        {
          "name": "Undetermined",
          "id": "und"
        }
      ]
    },
    {
      "name": "014 - groups and virtual keys",
      "id": "014 - groups and virtual keys",
      "version": "0.0",
      "languages": [
        {
          "name": "Undetermined",
          "id": "und"
        }
      ]
    },
    {
      "name": "015 - ralt 2",
      "id": "015 - ralt 2",
      "version": "0.0",
      "languages": [
        {
          "name": "Undetermined",
          "id": "und"
        }
      ]
    },
    {
      "name": "017 - space mnemonic kbd",
      "id": "017 - space mnemonic kbd",
      "version": "0.0",
      "languages": [
        {
          "name": "Undetermined",
          "id": "und"
        }
      ]
    },
    {
      "name": "018 - nul testing",
      "id": "018 - nul testing",
      "version": "0.0",
      "languages": [
        {
          "name": "Undetermined",
          "id": "und"
        }
      ]
    },
    {
      "name": "019 - multiple deadkeys",
      "id": "019 - multiple deadkeys",
      "version": "0.0",
      "languages": [
        {
          "name": "Undetermined",
          "id": "und"
        }
      ]
    },
    {
      "name": "020 - deadkeys and backspace",
      "id": "020 - deadkeys and backspace",
      "version": "0.0",
      "languages": [
        {
          "name": "Undetermined",
          "id": "und"
        }
      ]
    },
    {
      "name": "021 - options",
      "id": "021 - options",
      "version": "0.0",
      "languages": [
        {
          "name": "Undetermined",
          "id": "und"
        }
      ]
    },
    {
      "name": "022 - options with preset",
      "id": "022 - options with preset",
      "version": "0.0",
      "languages": [
        {
          "name": "Undetermined",
          "id": "und"
        }
      ]
    },
    {
      "name": "023 - options with save",
      "id": "023 - options with save",
      "version": "0.0",
      "languages": [
        {
          "name": "Undetermined",
          "id": "und"
        }
      ]
    },
    {
      "name": "024 - options with save and preset",
      "id": "024 - options with save and preset",
      "version": "0.0",
      "languages": [
        {
          "name": "Undetermined",
          "id": "und"
        }
      ]
    },
    {
      "name": "025 - options with reset",
      "id": "025 - options with reset",
      "version": "0.0",
      "languages": [
        {
          "name": "Undetermined",
          "id": "und"
        }
      ]
    },
    {
      "name": "026 - system stores",
      "id": "026 - system stores",
      "version": "0.0",
      "languages": [
        {
          "name": "Undetermined",
          "id": "und"
        }
      ]
    },
    {
      "name": "027 - system stores 2",
      "id": "027 - system stores 2",
      "version": "0.0",
      "languages": [
        {
          "name": "Undetermined",
          "id": "und"
        }
      ]
    },
    {
      "name": "028 - smp",
      "id": "028 - smp",
      "version": "0.0",
      "languages": [
        {
          "name": "Undetermined",
          "id": "und"
        }
      ]
    },
    {
      "name": "029 - beep",
      "id": "029 - beep",
      "version": "0.0",
      "languages": [
        {
          "name": "Undetermined",
          "id": "und"
        }
      ]
    },
    {
      "name": "030 - multiple groups",
      "id": "030 - multiple groups",
      "version": "0.0",
      "languages": [
        {
          "name": "Undetermined",
          "id": "und"
        }
      ]
    },
    {
      "name": "031 - caps lock.kmx",
      "id": "031 - caps lock.kmx",
      "version": "0.0",
      "languages": [
        {
          "name": "Undetermined",
          "id": "und"
        }
      ]
    }
  ]
}

=== keymanapp/keyman/developer/src/kmc-package/test/fixtures/kmp.json/kmp.json
{
  "system": {
    "keymanDeveloperVersion": "17.0.91.0",
    "fileVersion": "7.0"
  },
  "options": {
    "readmeFile": "readme.htm"
  },
  "startMenu": {
    "folder": "ahom_star",
    "addUninstallEntry": true,
    "items": [
      {
        "name": "(new)",
        "filename": "(Product Configuration)",
        "arguments": "shom_star"
      },
      {
        "name": "(new)",
        "filename": "Ahom_star.kvk",
        "arguments": "Ahom fonts"
      }
    ]
  },
  "info": {
    "version": {
      "description": "1.0.1"
    },
    "name": {
      "description": "Ahom Star"
    },
    "copyright": {
      "description": "\u00A9 2021-2022 HemantaGogoi Ngi Mon"
    },
    "author": {
      "description": "Dr Hemanta Kumar Gogoi",
      "url": "mailto:drhemanta97@gmail.com"
    }
  },
  "files": [
    {
      "name": "ahom_star.kvk",
      "description": ""
    },
    {
      "name": "ahom_star.kmx",
      "description": ""
    },
    {
      "name": "ahom_star.js",
      "description": ""
    },
    {
      "name": "welcome.htm",
      "description": ""
    },
    {
      "name": "desktop_layout_default.png",
      "description": ""
    },
    {
      "name": "desktop_layout_shift.png",
      "description": ""
    },
    {
      "name": "phone_default.png",
      "description": ""
    },
    {
      "name": "phone_longpress.png",
      "description": ""
    },
    {
      "name": "phone_numeric.png",
      "description": ""
    },
    {
      "name": "phone_shift.png",
      "description": ""
    },
    {
      "name": "readme.htm",
      "description": ""
    },
    {
      "name": "NotoSerifAhom-Regular.ttf",
      "description": ""
    },
    {
      "name": "kmp.inf",
      "description": ""
    },
    {
      "name": "kmp.json",
      "description": ""
    }
  ],
  "keyboards": [
    {
      "name": "Ahom Star",
      "id": "ahom_star",
      "version": "1.0.1",
      "oskFont": "NotoSerifAhom-Regular.ttf",
      "displayFont": "NotoSerifAhom-Regular.ttf",
      "languages": [
        {
          "name": "Ahom (Ahom)",
          "id": "aho-Ahom"
        }
      ]
    }
  ]
}

=== keymanapp/keyman/developer/src/kmc-package/test/fixtures/khmer_angkor/ref/kmp.json
{
  "system": {
    "keymanDeveloperVersion": "16.0.60.0",
    "fileVersion": "7.0"
  },
  "options": {
    "readmeFile": "readme.htm",
    "graphicFile": "splash.gif",
    "welcomeFile": "welcome.htm"
  },
  "info": {
    "name": {
      "description": "Khmer Angkor"
    },
    "copyright": {
      "description": "\u00A9 2015-2022 SIL International"
    },
    "author": {
      "description": "Makara Sok",
      "url": "mailto:makara_sok@sil.org"
    },
    "version": {
      "description": "1.3"
    },
    "website": {
      "description": "https://keyman.com/keyboards/khmer_angkor",
      "url": "https://keyman.com/keyboards/khmer_angkor"
    }
  },
  "files": [
    {
      "name": "khmer_angkor.js",
      "description": ""
    },
    {
      "name": "khmer_angkor.kvk",
      "description": ""
    },
    {
      "name": "khmer_angkor.kmx",
      "description": ""
    },
    {
      "name": "keyboard_layout.png",
      "description": ""
    },
    {
      "name": "welcome.htm",
      "description": ""
    },
    {
      "name": "FONTLOG.txt",
      "description": ""
    },
    {
      "name": "Mondulkiri-R.ttf",
      "description": ""
    },
    {
      "name": "OFL.txt",
      "description": ""
    },
    {
      "name": "OFL-FAQ.txt",
      "description": ""
    },
    {
      "name": "KAK_Documentation_EN.pdf",
      "description": ""
    },
    {
      "name": "KAK_Documentation_KH.pdf",
      "description": ""
    },
    {
      "name": "readme.htm",
      "description": ""
    },
    {
      "name": "image002.png",
      "description": ""
    },
    {
      "name": "khmer_busra_kbd.ttf",
      "description": ""
    },
    {
      "name": "splash.gif",
      "description": ""
    },
    {
      "name": "kmp.inf",
      "description": ""
    },
    {
      "name": "kmp.json",
      "description": ""
    }
  ],
  "keyboards": [
    {
      "name": "Khmer Angkor",
      "id": "khmer_angkor",
      "version": "1.3",
      "oskFont": "khmer_busra_kbd.ttf",
      "displayFont": "Mondulkiri-R.ttf",
      "languages": [
        {
          "name": "Central Khmer (Khmer, Cambodia)",
          "id": "km"
        }
      ]
    }
  ]
}

=== keymanapp/keyman/developer/src/kmc-package/test/fixtures/withfolders.qaa.sencoten/withfolders.qaa.sencoten.model.kmp.zipped.json
{
  "system": {
    "keymanDeveloperVersion": "12.0.1500.0",
    "fileVersion": "12.0"
  },
  "options": {},
  "info": {
    "author": {
      "description": "Eddie Antonio Santos",
      "url": "mailto:Eddie.Santos@nrc-cnrc.gc.ca"
    },
    "copyright": {
      "description": "© 2019 National Research Council Canada"
    },
    "name": {
      "description": "SENĆOŦEN (Saanich Dialect) Lexical Model"
    },
    "version": {
      "description": "1.0.3"
    }
  },
  "files": [
    {
      "name": "withfolders.qaa.sencoten.model.js",
      "description": "Lexical model withfolders.qaa.sencoten.model.js",
      "copyLocation": 0
    },
    {
      "copyLocation": 0,
      "description": "Welcome file",
      "name": "welcome.htm"
    }
  ],
  "lexicalModels": [
    {
      "name": "SENĆOŦEN dictionary",
      "id": "withfolders.qaa.sencoten",
      "languages": [
        {
          "name": "North Straits Salish",
          "id": "qaa"
        },
        {
          "name": "SENĆOŦEN",
          "id": "qaa-Latn"
        }
      ]
    }
  ]
}

=== keymanapp/keyman/developer/src/kmc-package/test/fixtures/example.qaa.sencoten/example.qaa.sencoten.model.kmp.intermediate.json
{
  "system": {
    "keymanDeveloperVersion": "12.0.1500.0",
    "fileVersion": "12.0"
  },
  "options": {},
  "info": {
    "author": {
      "description": "Eddie Antonio Santos",
      "url": "mailto:Eddie.Santos@nrc-cnrc.gc.ca"
    },
    "copyright": {
      "description": "© 2019 National Research Council Canada"
    },
    "name": {
      "description": "SENĆOŦEN (Saanich Dialect) Lexical Model"
    },
    "version": {
      "description": "1.0.3"
    }
  },
  "files": [
    {
      "name": "example.qaa.sencoten.model.js",
      "description": "Lexical model example.qaa.sencoten.model.js"
    },
    {
      "description": "Package information (JSON)",
      "name": "kmp.json"
    }
  ],
  "lexicalModels": [
    {
      "name": "SENĆOŦEN dictionary",
      "id": "example.qaa.sencoten",
      "languages": [
        {
          "name": "North Straits Salish",
          "id": "qaa"
        },
        {
          "name": "SENĆOŦEN",
          "id": "qaa-Latn"
        }
      ]
    }
  ]
}
